import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'autogenerated', dirName: 'guides' },
    {
      type: 'category',
      label: 'Types API',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'types-api/index'
      },
      items: require('./docs/types-api/typedoc-sidebar.cjs')
    },
    {
      type: 'category',
      label: 'Hooks API',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'hooks-api/index'
      },
      items: require('./docs/hooks-api/typedoc-sidebar.cjs')
    },
    {
      type: 'category',
      label: 'Utils API',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'doc',
        id: 'utils-api/index'
      },
      items: require('./docs/utils-api/typedoc-sidebar.cjs')
    }
  ]
};

export default sidebars;
